version: '2'

services:
  dockbix-agent-xxl:
    image: monitoringartist/dockbix-agent-xxl-limited:latest
    privileged: true
    network_mode: "host"
    volumes:
      - /:/rootfs
      - /var/run:/var/run
    environment:
      - ZA_Server=<ZABBIX SERVER IP/DNS NAME>
